- package_installs.R
The `fastknn` R package is described here https://github.com/davpinto/fastknn.
> Add fastknn to package installs

- Dockerfile
> Remove duplicate directive in rserver.conf

- package_installs.R
Also downloads Spark for use locally
> Install the latest version of sparklyr

- Dockerfile
- test_build.R
The R build has been broken for some months now.
* Use latest mxnet version compatible with the latest DiagrammeR package.
* --no-use-wheel flag has been removed in favor of --no-binary
* add tests for mxnet
This fixes the build
BUG=112431404
> mxnet incompatibility and pip new flag.

- bioconductor_installs.R
https://bioconductor.org/install
CI green: https://ci.kaggle.net/job/kernels/job/docker-rstats/job/bioconductor-ci/
b/135934783
> Install the new version of Bioconductor 

- package_installs.R
- tests/test_patchwork.R
> Install patchwork

- package_installs.R
- tests/test_topicmodels.R
> Install topicmodels

- package_installs.R
- tests/test_bayescl.R
- tests/test_imports.R
- tests/test_tensorflow.R
- Install `fslr` and `hrbrthemes` packages inside the `docker-rstats` while waiting for it to be fixed in `docker-rcran`.
- Added back the bayesCL test now that it is passing.
The build succeeded:
https://ci.kaggle.net/job/kernels/job/docker-rstats/job/clean-build/
> Clean build

- README.md
> Update README to include public GPU repo

- Dockerfile
- bioconductor_installs.R
- build
- package_installs.R
> Packages rcran are installed in docker-rcran instead

- Dockerfile
- test
- Upgrade to python 3.7
- Make sure to clean every layer
- Simple test to make sure nbconvert is working (TODO: will create a more complete test in a separate PR)
> Fix nbconvert

- Jenkinsfile
> Prune old R images from GPU worker

- Jenkinsfile
Fix race condition in concurrent builds.
Context:
The Jenkins pipeline allows building branches.
However, running multiple builds in parallel had a race.
Part of the pipeline is executed on a CPU-only agent and another part is executed on a GPU agent. Docker Images are transferred between these agents using the Registry but all the parallel builds were writing to the same image tag (race).
This ensures that a different Docker image tag is used when building different branches.
See similar fix implemented a year ago for the Python repo: https://github.com/Kaggle/docker-python/pull/492
BUG=154237926
> Avoid race condition in concurrent builds

- test
- tests/data/notebook.ipynb
- tests/test_nbconvert.R
> Test nbconvert 

- Dockerfile
Otherwise there is an error connecting to a notebook.
https://github.com/jupyter/notebook/issues/4437
Next: release and unit tests
> Install older version of tornado 

- gpu.Dockerfile
Use the same as for `docker-python` image.
> Refactor CUDA installation

- package_installs.R
> Remove unused largevis package

- Jenkinsfile
- diff
- tools/r_list_versions.R
Add build step to compare r package versions.
b/157548958
> Diff Package Versions

- Dockerfile
- gpu.Dockerfile
- tests/test_tensorflow.R
b/159364787
Note: I tried to upgrade to Tensorflow 2.2, but got issue detecting the GPU device with CUDA 10.1. Trying upgrading CUDA in a different branch.
> Upgrade to Tensorflow 2.0

- package_installs.R
> Fix Catboost installation

- Dockerfile
- gpu.Dockerfile
- tests/test_tensorflow.R
Also includes a required upgrade of CUDA.
b/159728071
> Upgrade to tensorflow 2.3

- tests/test_tidymodels.R
Test that tidymodels is properly installed, and that one of its package works as expected.
http://b/174050294
> tidymodels

- Dockerfile
- bioconductor_installs.R
> Fix devtools missing when installing bioconductor

- Dockerfile
- gpu.Dockerfile
> Upgrade to tf 2.4

- Jenkinsfile
> Post updates to Mattermost

- Jenkinsfile
> Fix mattermost notification

- Dockerfile
- package_installs.R
- By fixing SSL connections when downloading files/packages
- Unpin nbconvert
- Pin keras
http://b/185379627
> Fix rstats build

- Jenkinsfile
> Use main as default branch

- Jenkinsfile
Standardized with docker-rcran: https://github.com/Kaggle/docker-rcran/pull/57#discussion_r762150273
> Delete unversioned images after 6 months

- bioconductor_installs.R
- gpu.Dockerfile
- package_installs.R
Also pinning `locfit` which is a dependency of `EBImage` and the latest version doesn't work with this version of R.
http://b/224540778
> Pin torch package

- Dockerfile
- package_installs.R
- tests/test_jupyterlab-lsp.R
- tests/test_languageserver.R
> Install dependencies for LSP-based autocompletion in R kernels.

- package_installs.R
- tests/test_tfhub.R
> Install tfhub package

- Dockerfile
- gpu.Dockerfile
- test
- tests/test_keras.R
> Upgrade to CUDA 11.7

- gpu.Dockerfile
> Fix cuda image removed from docker

- Jenkinsfile
> Remove slack notifications

- Jenkinsfile
We will be relying on Artifact Registry cleanup policies instead.
http://b/321030221
> Remove process to delete old images
