Kaggle/docker-rstats

- Dockerfile
- package_installs.R
Hi,
I created the dataset:https://www.kaggle.com/ilknuricke/neurohackinginrimages the other day in order to implement the code from the coursera course Neurohacking in R (https://www.coursera.org/learn/neurohacking). I quickly realized that some additional packages were needed to run some of the code on Kaggle's  R notebooks environment.
This docker builds and runs successfully on my mac. If these could be incorporated into Kaggle, I believe it would make it much easier for the participants of that Coursera course to work on the stuff without having to install R or any of the packages themselves.
Thank you in advance,
Ilknur Icke
> Added fsl binary install and other 3rd party R packages

- package_installs.R
Microsoft's lightGBM is not available on CRAN yet so it needs to be loaded through the repo on github.
> Add lightGBM to Kernel image

- package_installs.R
The docker currently uses the version of H2O that is on CRAN which is sometimes a few versions behind. This will install the latest stable version of H2O.
> Install the latest stable version of H2O

- build
- test_build.R
This added test depends on ImageMagick's `convert` utility (and perhaps more) to
be installed.  That dependency is expected to be satisfied by `kaggle/rcran`.
> Ensure gganimate works.

- Dockerfile
Fixes error: 
```
Sep 07 00:10:16 [0m[91mFetched in submodule path '3rdparty/nnvm/tvm', but it did not contain fdba6cc9bd3bec9ccd0592fa3900b7fe25d6cb97. Direct fetching of that commit failed.
```
> Branch 1.2.0 references a bad commit for the nnvm/tvm submodule

- package_installs.R
- test_build.R
Fails installing on master:
```
Sep 20 12:48:15   --quiet CMD INSTALL  \
Sep 20 12:48:15   '/tmp/RtmpXvHCeI/devtools5485220c7ee2/Microsoft-LightGBM-425503d/R-package'  \
Sep 20 12:48:15   --library='/usr/local/lib/R/site-library' --install-tests 
Sep 20 12:48:15 
Sep 20 12:48:15 [0m[91m* installing *source* package 'lightgbm' ...
Sep 20 12:48:15 [0m[91m** libs
Sep 20 12:48:15 [0mgcc -I/usr/local/lib/R/include -DNDEBUG   -I/usr/local/include   -fpic  -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c R_init.c -o R_init.o
Sep 20 12:48:15 gcc -shared -L/usr/local/lib/R/lib -L/usr/local/lib -o lightgbm.so R_init.o -L/usr/local/lib/R/lib -lR
Sep 20 12:48:15 [91minstalling via 'install.libs.R' to /usr/local/lib/R/site-library/lightgbm
Sep 20 …
```
> lightgbm master is broken, pin to latest stable version

- build
- Consistent with the `docker-python` build script
- Support short flag
- Print help & error message when using wrong flags
> Improve build script

- package_installs.R
Latest version fails to build. Pinning to the currently released version in Kaggle Kernels.
> Fix catboost build

- package_installs.R
My PR to fix an upstream bug has been merged:
https://github.com/dselivanov/LSHR/pull/14
> Remove version pinning for LSHR

- package_installs.R
These packages fails to install and are not present on the currently released image.
> remove packages that weren't installed

- package_installs.R
This reverts commit f70e4887e293fb6162e5bbb1e74991987753ac70.
Requires one more PR to get merged before we can install from master: https://github.com/dselivanov/LSHR/pull/15
> Revert "Remove version pinning for LSHR"

- Dockerfile
- Jenkinsfile
- build
- clean-layer.sh
- gpu.Dockerfile
- push
- test
- Added a `gpu.Dockerfile` that adds layer on top of the CPU `rstats` image to install cuda and GPU specific packages
- Updated the `build`, `test` and `push` script to add a `--gpu` flag to support handling GPU Docker image.
- Updated the `Jenkinsfile` to have one pipeline building both the CPU and GPU images off the `master` branch.
> Merge cuda branch into master

- Jenkinsfile
To avoid conflicts between the `docker-stats` and the `docker-python` pipeline.
> Remove only dangling images between test run.

- Dockerfile
> Fix mxnet build.

- Dockerfile
This adds a 3.6 miniconda env that shouldn't (fingers crossed) interfere with the coexisting python 2.7/tensorflow installation. I skip typical anaconda steps like adding conda to bash and activating the env so that it doesn't become the system's default python.
> Add miniconda ci

- package_installs.R
Installation failed because of dependent package:
```
Nov 27 21:28:58 [91mERROR: lazy loading failed for package ‘pitchRx’
Nov 27 21:28:58 [0m[91m* removing ‘/usr/local/lib/R/site-library/pitchRx’
Nov 27 21:28:58 [0m[91mError: Failed to install 'baseballr' from GitHub:
Nov 27 21:28:58   (converted from warning) installation of package ‘pitchRx’ had non-zero exit status
Nov 27 21:28:58 Execution halted
The command '/bin/sh -c Rscript /tmp/package_installs.R' returned a non-zero code: 1
```
Users can use the following to install it in their own kernel (when master is fixed or picking a known good commit):
```
library(devtools)
install_github("BillPetti/baseballr", force = TRUE)
```
> Remove baseballr package

- Dockerfile
https://irkernel.github.io/installation/
It was failing with this message: 
```
Feb 20 18:18:18 > IRkernel::installspec()
Feb 20 18:18:18 [91mError in loadNamespace(name) : there is no package called ‘IRkernel’
```
> Install IRkernel properly

- Jenkinsfile
This will increase our GitHub rate limit from 60 calls / hour to 5000 calls / hour.
The token has a single permission:
* read public repo
This will increase our rate limit to avoid build failures like:
```
Mar 26 01:01:39  [0m [91mError: Failed to install 'unknown package' from GitHub:
Mar 26 01:01:39   HTTP error 403.
Mar 26 01:01:39   API rate limit exceeded for 35.231.143.114. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)
Mar 26 01:01:39 
Mar 26 01:01:39   Rate limit remaining: 0/60
Mar 26 01:01:39   Rate limit reset at: 2020-03-26 01:46:37 UTC
```
BUG=152450512
> Set GITHUB_PAT env var from Jenkins credentials store

- Dockerfile
- build
- gpu.Dockerfile
Equivalent to the `build` script for the Python image:
https://github.com/Kaggle/docker-python/blob/master/build#L12
Next:
- Avoid race condition in parallel build like what was done here for the Python image: https://github.com/Kaggle/docker-python/pull/492
154237926
> Add --base-image-tag to build script

- Dockerfile
- build
Similar to what was done for the Python image:
https://github.com/Kaggle/docker-python/blob/master/Dockerfile#L494-L501
> Add git-commit & build-date LABELS to image.

- Jenkinsfile
- push
There are no guarantees that the worker running the `push` step is the same than the `build` step.
For instance, if you have 2 workers: A & B.
A may build the image.
B may push the image.
In which case, the build fails with:
```
Error response from daemon: No such image: kaggle/python-gpu-build:latest
```
> Ensure the image to push is present on the worker

- gpu.Dockerfile
- ldpaths
This is hopefully a temporary solution.
Original `ldpaths` file content: 
```
: ${JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64}
: ${R_JAVA_LD_LIBRARY_PATH=${JAVA_HOME}/lib/server}
if test -n "/usr/local/lib:/usr/lib/x86_64-linux-gnu"; then
: ${R_LD_LIBRARY_PATH=${R_HOME}/lib:/usr/local/lib:/usr/lib/x86_64-linux-gnu}
else
: ${R_LD_LIBRARY_PATH=${R_HOME}/lib}
fi
if test -n "${R_JAVA_LD_LIBRARY_PATH}"; then
R_LD_LIBRARY_PATH="${R_LD_LIBRARY_PATH}:${R_JAVA_LD_LIBRARY_PATH}"
fi
if test -z "${LD_LIBRARY_PATH}"; then
LD_LIBRARY_PATH="${R_LD_LIBRARY_PATH}"
else
LD_LIBRARY_PATH="${R_LD_LIBRARY_PATH}:${LD_LIBRARY_PATH}"
fi
export LD_LIBRARY_PATH
```
Instead of setting `/usr/lib/x86_64-linux-gnu` in front of the path, it's moved at the end.
> Fix gpu by changing the path set by R

- Dockerfile
- tests/test_papermill.R
papermill provides a bunch of nice features for executing notebooks, including ones not provided by nbconvert.
Some key features we want:
- dump cell output to logs
- stop on cell error, but still include cell output up to the errored cell
> pip install papermill

- Jenkinsfile
This way, we avoid the risk of releasing a CPU and GPU image from 2 different builds.
BUG=157163453
> Add staging tag to images at the end of build pipeline

- package_installs.R
By default, the version from `master` is installed which is unstable.
BUG=157415837
> Install specific version of LightGBM

- gpu.Dockerfile
They both fail to install and haven't been used by Kagglers for at least 2 months.
> Remove gpuR and kmcudaR

- Dockerfile
The CPU image was tested against e2e tests.
b/170301227
> Pin nbconvert as the version 6 has a bug

- kaggle/kaggle_bigquery.R
- kaggle/kaggle_secrets.R
Similarly to clients in python, we want to pass IAP token in staging to allow testing in that environment.
The token is passed to the notebook via env variable, and then used to communicate with IAP.
http://b/158655418#comment33
> Pass IAP token if present for requests from R container

- Dockerfile
- build
To avoid conflict with an homonymous environment variable coming from the `rcran` image.
```
❯ docker run -it gcr.io/kaggle-images/rstats:build-date-bug-staging /bin/bash
root@fabf64a0b878:/# cat /etc/build_date
20210318-132538
```
http://b/183049196
> Use a unique name for the build date argument

- Dockerfile
- kaggle/template_conf.json
- nbconvert-extensions.tpl
- tests/test_nbconvert.R
Use the non-deprecated nbconvert template and add template configuration file.
The config is a breaking change in nbconvert 6.x
Also added a unit test to cover this kind of breakage, before we create new SDGs.
http://b/170301227
> Fix nbconvert template

- Dockerfile
- package_installs.R
Changes: 
- Use rcran with R 4.0.5
- Upgrade mxnet to 1.8
- Use miniconda to install keras and tensorflow
- Make sure to install `imager` which wasn't properly installed on rcran
http://b/179893188
> Upgrade to R 4.0.5 base image

- Dockerfile
- test
Fix python installation; and test that papermill is installed in python.
http://b/191304257
> Fix papermill 

- Jenkinsfile
- Delete only images without the `v*` tag.
- Delete only images older than 9 months (recent unversioned images are
useful for debugging).
http://b/208859194
> Delete old unversioned rstats images

- Dockerfile
- gpu.Dockerfile
- package_installs.R
We can't install this version until the nvidia driver is upgraded on the COS image (https://b.corp.google.com/issues/208428716#comment4).
Let's revert this PR in order to keep the repo clean until we can do this upgrade.
http://b/208428716
> Revert "Upgrade to tensorflow 2.6"

- package_installs.R
The package was archived on RCRAN due to `neurobase` (one of its dependencies) being archived because of:
```
Archived on 2022-04-18 as 'coercion to logical' errors were not corrected in time.
```
Installing directly from GitHub.
http://b/232137539
> Install fslr in rstats

- tests/test_jupyterlab-lsp.R
Turns out this was still failing because lots of http requests throw errors. Now we handle those errors, check that we got a response back, and that it is a 200 code.
I also noticed that the system command was returning the exit code, not the pid, so I fixed that.
> Handle errors in jupyterlab-lsp test
